version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud9-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19oyz178snvic"
s3_prefix = "cloud9-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
